### ISSUE TITLE
KeyError: 'Text'

### ISSUE THREAD

**Issue by stevenleea** [brandonlou/DayOne2Joplin#1]
Thank you for making this code. I am a newbie regarding Python, so I read the instructions on Readme and did install Python 3 with Homebrew before. And I encounter this problem when running the 'python3 dayone2joplin from_dayone to_joplin' code.

![Screen Shot 2020-09-06 at 17 10 36](https://user-images.githubusercontent.com/5520904/92323680-e35adc80-f064-11ea-8219-fe95b51fe932.png)

Can you please help? Thank you.

**Comment by brandonlou** [comment]
Hi @stevenleea, thanks for reporting this issue! I think this problem occurred because there were journal entries with no content in them. I made some fixes and please let me know if it works :)

**Comment by brandonlou** [comment]
@stevenleea Any update on whether or not the KeyError bug is fixed on your end? I will be closing this issue soon otherwise.

**Comment by stevenleea** [comment]
Sorry for late response. Let me try it again now.

**Comment by stevenleea** [comment]
Hi Brandon, thank you for the fix. It works smoothly now. May I add a suggestion? I see the file name created in 'to_joplin' folder is using the post ID. Instead of that, why not use the post created_time for the file name? Like 2013-Dec-06_14-27-15.md for example.

Hopefully you consider it and the converter will run flawlessly. Thank you again, the code helps a lot.

**Comment by brandonlou** [comment]
@stevenleea Thanks again for reporting the bug! I agree using the date as the filename would make things more readable. When I was testing out the Joplin export feature they used ids as the filename. Different names might work, but I haven't tested it and I couldn't find any official documentation on Joplin's file organization.
