### ISSUE TITLE
File is not always 'Journal.json'

### ISSUE THREAD

**Issue by thibaultseynaeve** [brandonlou/DayOne2Joplin#3]
First of all, thanks a lot for this! This is awesome and saved me so much time. 
I followed the instructions you provided and got an error that the file Journal.json doesn't exist. It turns out that - since my Day One is set to Dutch - my file was called Dagboek.json.

After renaming it to Journal.json everything worked great :) 

Maybe you could expand the readme with a line that says something like "check if the json file is called Journal.json, if it's different please rename to Journal.json"

**Comment by brandonlou** [comment]
Hi @thibaultseynaeve, thank you for your suggestion! I have fixed this in 45b19fb.
