### ISSUE TITLE
Click File -> Export -> RAW - Joplin Export Directory

### ISSUE THREAD

**Issue by thibaultseynaeve** [brandonlou/DayOne2Joplin#4]
In the readme, step 2 of importing to Joplin is: 

Click File -> Export -> RAW - Joplin Export Directory.

I guess this should be:
Clickx File -> **Import** -> RAW - Joplin Export Directory

**Comment by brandonlou** [comment]
Thank you for the catch! Fixed in 9ffc103. I'm glad this code helped you :)
